# NumPy                          

### Basics

 Numpy (Numerical Python), is one of the most important foundational packages for numerical computing in Python.

1. NumPy is a crucial library in data science, offering essential data structures, computations, and integrations that enable efficient data manipulation, analysis, and machine learning.

2. NumPy operations can handle complex computations on entire arrays, eliminating the need for Python for loops.

3. NumPy is vital in data science as it forms the basis for data manipulation and computation, allowing data scientists to efficiently and effectively manage large datasets.

4. NumPy is a foundational tool in Python-based data science, enabling efficient and powerful numerical data manipulations that are critical for analysis, modeling, and visualization tasks.

5. Computations that utilize vectorization.

#### Installing and importing numpy library

In [1]:
# installing numpy library
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


you can install numpy library by using the above piece of code in your jupyter ipynb notebook

In [2]:
import numpy as np

#### Numpy array

In [3]:
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
## The data type of an array.
arr.dtype

dtype('int32')

In [5]:
## change the data type of an array.
a=np.array(arr,dtype=np.float64)
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [6]:
#Element wise operation
arr=arr*2
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [7]:
## Another function astype() to change the data type of an array.
float_arr=arr.astype(np.float64)
float_arr

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16.])

In [8]:
## arange() is a function in numpy returns a new array with evenly spaced values with given range.
arr1=np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [9]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
## Creating random elements
arr2=np.random.randn(2,3)
arr2

array([[-1.35493066, -0.0236461 , -0.20862808],
       [ 0.22493776,  1.84524384, -0.0443058 ]])

In [11]:
## Accessing element from numpy array.
arr[-1]

16

In [12]:
## Creating a numpy array with evenly spaced values over a specified range.
a=np.linspace(2,10,5,dtype='int')
a

array([ 2,  4,  6,  8, 10])

In [13]:
## Creating an numpy array with evenly spaced values on log scale.
a1=np.logspace(2,10,5)
a1

array([1.e+02, 1.e+04, 1.e+06, 1.e+08, 1.e+10])

linspace: Use when you need evenly spaced numbers between two points on a linear scale.

logspace: Use when you need evenly spaced numbers on a logarithmic scale, ideal for handling ranges that span several orders of magnitude.

#### Reshaping numpy array
you can reshape the array with reshape function

In [14]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [15]:
arr=arr.reshape(4,2)
arr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

A `ValueError` occurs when the total number of elements in the array does not match the product of the dimensions in the specified new shape; ensure the new shape exactly fits all elements in the array.

In [16]:
arr=arr.reshape(3,3)
arr

ValueError: cannot reshape array of size 8 into shape (3,3)

### Manipulating data using numpy

In [17]:
## UNIQUE ELEMENTS: Find unique elements in an array.

arr=np.array([9,3,2,8,9,2,9,4,5,9,2,8,3,9,4,5,6,1,2,6])
print(f"Unique elements:{np.unique(arr)}")

Unique elements:[1 2 3 4 5 6 8 9]


In [18]:
## TRANSPOSE: Swap the axes of an array.

arr=np.array([[1,2,3],[9,4,5]])
print(f"Transposed Array:")
print(arr.T)

Transposed Array:
[[1 9]
 [2 4]
 [3 5]]


In [19]:
## CONCATENATION: Join arrays together.

arr1=np.array([1,2,3])
arr2=np.array([7,8,9,10])
print(f"Contenated Array : {np.concatenate((arr1,arr2))}")

Contenated Array : [ 1  2  3  7  8  9 10]


In [20]:
## SORTING ELEMENTS: Sort elements of an array.

arr=np.array([52,98,65,43,21,78,60,77,54])
print(f"Sorted Array : {np.sort(arr)}")

Sorted Array : [21 43 52 54 60 65 77 78 98]


In [21]:
## INDEXING and SLICING: Selects specific elements or subsets of an array.

arr=np.array([[1,2],[3,4]])
sliced_arr=arr[0:1,1:2]
print(f"Sliced Array : {sliced_arr}")

Sliced Array : [[2]]


In [22]:
## SPLITING: Splits an array into multiple sub arrays.

arr=np.array([1,2,3,4,5,6,7,8])
print("splits to 4 equal parts")
print(f"Splitted Array: {np.split(arr,4)}")
print("splits to 2 equal parts")
print(f"Splitted Array: {np.split(arr,2)}")

splits to 4 equal parts
Splitted Array: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
splits to 2 equal parts
Splitted Array: [array([1, 2, 3, 4]), array([5, 6, 7, 8])]


### Aggregate data using NumPy

In [23]:
data = np.array([15,20,25,30,35,40,45,50])

In [24]:
#you can find the sum of all the elements in the array by using sum() function
print(f"Sum: {np.sum(data)}")

Sum: 260


In [25]:
#you can find the mean of all the elements in the array by using mean() function
print(f"Mean: {np.mean(data)}")

Mean: 32.5


In [26]:
#you can find the median of all the elements in the array by using median() function
print(f"Median: {np.median(data)}")

Median: 32.5


In [27]:
#you can find the Standarad deviation of all the elements in the array by using std() function
print(f"Standarad deviation: {np.std(data)}")

Standarad deviation: 11.4564392373896


In [28]:
#you can find the Minimum element of all the elements in the array by using min() function
print(f"Minimum element: {np.min(data)}")

Minimum element: 15


In [29]:
#you can find the Maximum element: of all the elements in the array by using max() function
print(f"Maximum element: {np.max(data)}")

Maximum element: 50


### Analyze data using NumPy

In [30]:
data=[85, 90, 78, 92, 88, 76,np.NaN, 95, 89, 84, 90]

In [31]:
scores=np.array(data)

In [32]:
scores

array([85., 90., 78., 92., 88., 76., nan, 95., 89., 84., 90.])

In [33]:
#Handling missing data
scores = np.nan_to_num(scores, nan=75)

In [34]:
print(f"Highest score in Python : {np.max(scores)}")

Highest score in Python : 95.0


In [35]:
print(f"Least score in Python : {np.min(scores)}")

Least score in Python : 75.0


In [36]:
print(f"Average score in Python : {np.average(scores)}")

Average score in Python : 85.63636363636364


In [37]:
#Filter data
filtered_data = scores[scores > 85]
filtered_data 

array([90., 92., 88., 95., 89., 90.])

### Conclusion

The notebook provides a comprehensive overview of NumPy, focusing on its array manipulation capabilities and its use for various mathematical and statistical operations. It is a helpful guide for anyone looking to understand the basics and some advanced functionalities of NumPy. The examples cover a wide range of applications, demonstrating the versatility and power of NumPy in data science and numerical computing tasks.